name: New Release Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publishToVSMarketplace:
        description: "Publish to VS Code Marketplace"
        required: false
        type: boolean
        default: true
      publishToOpenVSX:
        description: "Publish to Open VSX Registry"
        required: false
        type: boolean
        default: true


#Cancel running builds if another push to branch is made while this build is running
concurrency:
  group: release-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  createReleaseVersion:
    name: Validate Version Number
    uses: ./.github/workflows/versionBump.yml
    secrets: inherit
    permissions:
      checks: write
      contents: write
    with:
      pre-release: false
      ref: main

  buildAndPackageRelease:
    name: Build and Package
    uses: ./.github/workflows/buildAndPackage.yml
    secrets: inherit
    needs: createReleaseVersion
    permissions:
      checks: write
      contents: write
    with:
        pre-release: false
        ref: v${{ needs.createReleaseVersion.outputs.newVersion }}

  updateDevelopment:
    name: Update Development Branch
    runs-on: ubuntu-latest
    needs: buildAndPackageRelease
    if: needs.createReleaseVersion.outputs.isPatch == false
    steps:
      - name: Checkout Development Branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: development

      - name: Set up Git user
        run: |
          git config user.name "Github Actions"
          git config user.email "info@ortussolutions.com"

      - name: Fetch all branches
        run: git fetch origin main

      - name: Merge main into development
        run: |
          git merge origin/main --no-edit

      - name: Push changes
        run: git push origin development

  doPreRelease:
    name: Do Pre-Release
    needs: updateDevelopment
    uses: ./.github/workflows/preRelease.yml
    secrets: inherit
    permissions:
      checks: write
      contents: write

  publishMS:
    name: Publish to VS marketplace
    runs-on: ubuntu-latest
    needs: [ doPreRelease, buildAndPackageRelease ]
    # Run if triggered by push OR if manually triggered with publishToVSMarketplace enabled
    if: ${{ always() && (github.event_name == 'push' || inputs.publishToVSMarketplace == true) }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v5
        with:
          name: ${{ needs.buildAndPackageRelease.outputs.packageName }}
          path: .tmp

      - name: Publish to VS marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          ls .tmp
          npx vsce publish --packagePath .tmp/${{ needs.buildAndPackageRelease.outputs.packageName }}

  publishOpenVSX:
    name: Publish to Open VSX
    runs-on: ubuntu-latest
    needs: [ doPreRelease, buildAndPackageRelease ]
    # Run if triggered by push OR if manually triggered with publishToOpenVSX enabled
    if: ${{ always() && (github.event_name == 'push' || inputs.publishToOpenVSX == true) }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v5
        with:
          name: ${{ needs.buildAndPackageRelease.outputs.packageName }}
          path: .tmp

      - name: Publish to Open VSX Registry
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: |
          ls .tmp
          npx ovsx publish .tmp/${{ needs.buildAndPackageRelease.outputs.packageName }} -p $OVSX_PAT
