name: Pre-Release Extension

on:
  push:
    branches:
      - development
  workflow_dispatch:
  workflow_call:


# Cancel running builds if another push to branch is made while this build is running
concurrency:
  group: preRelease-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validatePreReleaseVersion:
    name: Validate Version Number
    uses: ./.github/workflows/versionBump.yml
    secrets: inherit
    permissions:
      checks: write
      contents: write
    with:
      pre-release: true
      ref: development


#   check if version number is correct for a prerelease
#   if not fail

  buildAndPackage:
    name: Build and Package
    uses: ./.github/workflows/buildAndPackage.yml
    secrets: inherit
    needs: validatePreReleaseVersion
    permissions:
      checks: write
      contents: write
    with:
        pre-release: true
        ref: development

  publishMS:
    name: Publish to VS marketplace
    runs-on: ubuntu-latest
    needs: buildAndPackage
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.buildAndPackage.outputs.packageName }}
          path: .tmp

      - name: Publish to VS marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          ls .tmp
          npx vsce publish --packagePath .tmp/${{ needs.buildAndPackage.outputs.packageName }} --pre-release
