name: Test
on:
    push:
        branches:
            - build-test
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                ssh-key: ${{ secrets.boxlang_ssh_key }}
                repository: organization_name/repo_name
